version: 2.0

workflows:
  version: 2
  build:
    jobs:
      - "ruby-2.5"
      - "ruby-2.6"
      - "ruby-2.7"

jobs:
  "ruby-2.5":
    docker:
      - image: ruby:2.5
      - image: amazon/dynamodb-local
        environment:
          MAX_HEAP_SIZE: 1024m
          HEAP_NEWSIZE: 512m

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "Appraisals" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            gem update bundler
            bundle install
            bundle exec appraisal install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "Appraisals" }}
      - run:  bundle exec appraisal rspec --format progress

  "ruby-2.6":
    docker:
      - image: ruby:2.6
      - image: amazon/dynamodb-local
        environment:
          MAX_HEAP_SIZE: 1024m
          HEAP_NEWSIZE: 512m

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "Appraisals" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            gem update bundler
            bundle install
            bundle exec appraisal install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "Appraisals" }}
      - run: bundle exec appraisal rspec --format progress

  "ruby-2.7":
    docker:
      - image: ruby:2.7
      - image: amazon/dynamodb-local
        environment:
          MAX_HEAP_SIZE: 1024m
          HEAP_NEWSIZE: 512m

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "Appraisals" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            gem update bundler
            bundle install
            bundle exec appraisal install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "Appraisals" }}
      - run: bundle exec appraisal rspec --format progress






